name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.0'  # Adjust this to the version of Python you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pylint

    - name: Run Pytest
      run: |
        pytest --cov --pylint  --cov-fail-under=100
      env:
        CI: true

    - name: Run Pylint
      run: |
        pylint your_package_name/
      continue-on-error: false

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Fail the job if tests, coverage or pylint don't pass
      if: failure()
      run: exit 1
